# payment-service — base config
server:
  port: 8085

spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    consumer:
      group-id: payment-service-group

banking:
  payment:
    outbox-poll-interval-ms: 5000
    swift:
      bic: BANKUS33XXX
      correspondent-bank-bic: CHASUS33
    limits:
      swift-max-amount: 10000000.00
      ach-max-amount: 25000.00
      internal-max-amount: 1000000.00

springdoc:
  api-docs:
    path: /v3/api-docs
